# Generated by Django 3.2.17 on 2023-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_remove_resume_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobexp',
            field=models.CharField(max_length=100, verbose_name='jobexp'),
        ),
    ]
