# Generated by Django 3.2.17 on 2023-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_job_jobexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobdescription',
            field=models.FileField(upload_to='desc/', verbose_name='jobdescription'),
        ),
    ]
