# Generated by Django 3.2.17 on 2023-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_job_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobdate',
            field=models.DateField(verbose_name='jobdate'),
        ),
    ]
