# Generated by Django 3.2.17 on 2023-03-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_alter_job_jobdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='p',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qa1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qa2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qa3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qa4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qc1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qc2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qc3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qc4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qe1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qe2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qe3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qe4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qn1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qn2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qn3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qn4',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qo1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qo2',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qo3',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='qo4',
        ),
    ]
