# Generated by Django 3.2.17 on 2023-03-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_resume_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='jobs',
        ),
    ]
