# Generated by Django 3.2.17 on 2023-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_remove_resume_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='jobs'),
        ),
    ]
