# Generated by Django 3.2.17 on 2023-03-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_resume_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='p2',
        ),
    ]
