# Generated by Django 3.2.17 on 2023-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_auto_20230330_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='matchpercentage',
            field=models.DecimalField(decimal_places=100, default=0.0, max_digits=100),
            preserve_default=False,
        ),
    ]
