# Generated by Django 3.2.17 on 2023-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_alter_resume_matchpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='short',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
