# Generated by Django 3.2.17 on 2023-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_alter_resume_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='short',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
