# Generated by Django 3.2.17 on 2023-04-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_alter_resume_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='short',
        ),
    ]
