# Generated by Django 3.2.17 on 2023-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_remove_resume_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='matchpercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Match Percentage'),
            preserve_default=False,
        ),
    ]
