# Generated by Django 3.2.17 on 2023-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_alter_resume_matchpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='matchpercentage',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Match Percentage'),
        ),
    ]
