# Generated by Django 3.2.17 on 2023-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0018_resume_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='short2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
