# Generated by Django 3.2.17 on 2023-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0019_resume_short2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobexp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
