# Generated by Django 3.2.17 on 2023-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0020_alter_job_jobexp'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('user_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Comment')),
            ],
        ),
    ]
