# Generated by Django 3.2.17 on 2023-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0021_contactcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('recruiter_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('recruiter_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Password')),
                ('recruiter_confirm_password', models.CharField(blank=True, max_length=20, null=True, verbose_name='Confirm Password')),
            ],
        ),
    ]
