# Generated by Django 3.2.17 on 2023-05-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parser_app', '0022_recruiters'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='u_name_entry',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
