# Generated by Django 3.2.17 on 2023-05-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0023_applicants_u_name_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='u_name_entry',
        ),
    ]
